// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbxonuch1lxoYShpBNiajCegU-uWH2Gf4',
    appId: '1:249127948591:web:08cac898ff404be6ed11da',
    messagingSenderId: '249127948591',
    projectId: 'ggi-canteen',
    authDomain: 'ggi-canteen.firebaseapp.com',
    storageBucket: 'ggi-canteen.firebasestorage.app',
    measurementId: 'G-RKEW4RX1LT',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGGwlhX93idt27swAa1kLF8HIARNJEJqs',
    appId: '1:249127948591:ios:7bb30e9a52e82030ed11da',
    messagingSenderId: '249127948591',
    projectId: 'ggi-canteen',
    storageBucket: 'ggi-canteen.firebasestorage.app',
    iosBundleId: 'com.example.ggiCanteen',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGGwlhX93idt27swAa1kLF8HIARNJEJqs',
    appId: '1:249127948591:ios:7bb30e9a52e82030ed11da',
    messagingSenderId: '249127948591',
    projectId: 'ggi-canteen',
    storageBucket: 'ggi-canteen.firebasestorage.app',
    iosBundleId: 'com.example.ggiCanteen',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnWkGckLiy35zci6kh1t2uIas6P7imxNw',
    appId: '1:249127948591:android:8e61ddb5fe36ba5aed11da',
    messagingSenderId: '249127948591',
    projectId: 'ggi-canteen',
    storageBucket: 'ggi-canteen.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbxonuch1lxoYShpBNiajCegU-uWH2Gf4',
    appId: '1:249127948591:web:602270b260505997ed11da',
    messagingSenderId: '249127948591',
    projectId: 'ggi-canteen',
    authDomain: 'ggi-canteen.firebaseapp.com',
    storageBucket: 'ggi-canteen.firebasestorage.app',
    measurementId: 'G-KS1CFZPRQY',
  );

}